### ISSUE TITLE
ModuleNotFoundError: No module named 'pyvista._vtk'

### ISSUE THREAD

**Issue by j-otsuki** [CMT-MU/QtDraw#1]
最新のpyvista 0.41.1でこのエラーが出ました。
pyvistaのバージョンをひとつづつ下げていったら、0.39.1でエラーが消えました。

ご対応いただけると助かります。

大槻

---

エラーメッセージ
```
Traceback (most recent call last):
  File "/home/otsuki/.local/bin/qtdraw", line 33, in <module>
    sys.exit(load_entry_point('qtdraw', 'console_scripts', 'qtdraw')())
  File "/home/otsuki/.local/bin/qtdraw", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/otsuki/gitclones/QtDraw/qtdraw/scripts/qtdraw.py", line 5, in <module>
    from qtdraw.qt_draw import QtDraw
  File "/home/otsuki/gitclones/QtDraw/qtdraw/qt_draw.py", line 18, in <module>
    from qtdraw.core.util import create_unit_cell, plot_axis, view_vectors, create_application     
  File "/home/otsuki/gitclones/QtDraw/qtdraw/core/util.py", line 3, in <module>
    from pyvista._vtk import vtkParametricSpline
ModuleNotFoundError: No module named 'pyvista._vtk'
```

workaround
```
$ pip install pyvista==0.39.1
```

**Comment by aoymt** [comment]
qtdraw/core/util.py の 3行目を
from vtk import vtkParametricSpline
に書き換えると問題が解消します。(pyvista 0.41.1)
ご参考まで。

**Comment by j-otsuki** [comment]
ありがとうございます！
